################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../application_properties.c \
../dtm.c \
../dtm_usart.c \
../gatt_db.c \
../init_app.c \
../init_board.c \
../init_mcu.c \
../main.c \
../pti.c 

OBJS += \
./application_properties.o \
./dtm.o \
./dtm_usart.o \
./gatt_db.o \
./init_app.o \
./init_board.o \
./init_mcu.o \
./main.o \
./pti.o 

C_DEPS += \
./application_properties.d \
./dtm.d \
./dtm_usart.d \
./gatt_db.d \
./init_app.d \
./init_board.d \
./init_mcu.d \
./main.d \
./pti.d 


# Each subdirectory must supply rules for building sources it contributes
application_properties.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"application_properties.d" -MT"application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

dtm.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/dtm.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"dtm.d" -MT"dtm.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

dtm_usart.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/dtm_usart.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"dtm_usart.d" -MT"dtm_usart.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gatt_db.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gatt_db.d" -MT"gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_app.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_app.d" -MT"init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_board.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_board.d" -MT"init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_mcu.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_mcu.d" -MT"init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pti.o: /Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/pti.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DEFR32BG13P632F512GM48=1' -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/common" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/protocol/bluetooth/ble_stack/inc/soc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/radio/rail_lib/chip/efr32" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/hardware/kit/EFR32BG13_BRD4104A/config" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm" -I"/Users/clfilho/SimplicityStudio/v4_workspaceN/soc-dtm/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pti.d" -MT"pti.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


